[package]
name = "connect-4-rust"
version = "0.6.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"

# In Cargo.toml Optimize for size
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1